import './globals.css'
import Navbar from "@/companents/navbar/Navbar";
import Footer from "@/companents/footer/Footer";
import {ThemeProvider} from "@/context/ThemeContext";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
      <ThemeProvider >
          <div>
              <Navbar />
              {children}
              <Footer />
          </div>

      </ThemeProvider>

      </body>
    </html>
  )
}
